/**
 * Shunt — browser demo.
 *
 * The four shaders below are copied unedited from `source/Shaders.cpp`,
 * including the `#ifdef SHUNT_EFFECT` branches — the two bundles really are one
 * pair of shaders compiled twice, and the picker in the transport bar compiles
 * them both ways here for the same reason. `withDefines()` inserts the define
 * after the `#version` line exactly as `Shunt.cpp` does, and
 * `demo/tools/check_shaders.py` compares the two copies character for character
 * so they cannot drift.
 *
 * `Queue.cpp` is ported below in full, with `Shapes.cpp`'s extents and bounds
 * and `Controls.cpp`'s 0..1 conversions. That port is the interesting part of
 * this page, because it is the plugin's whole design:
 *
 * **A shape's place is a pure function of (slot, phase).** There is no queue
 * object that shapes are pushed onto and popped off, no "has the one in front
 * left yet?" test, no previous frame. Drag the transport anywhere and the
 * picture is exact, because the frame at phase 91.7 does not need the preceding
 * 91.7 to have been played.
 *
 * What makes that work is the slide speed being derived rather than set:
 * `(1 + 2·margin) / (1 − dwell)` makes every shape's run exactly one cycle long
 * whatever slot it stands at, so `count` shapes released one per `1/count` of a
 * cycle tile the cycle exactly — always that many in play, never a hole and
 * never two shapes wanting one slot.
 */

import { mountDemo } from './vendor/demo.js';
import { Program, bindTexture } from './vendor/gl.js';

//===========================================================================
// The shaders. Copied from source/Shaders.cpp.
//===========================================================================

// --- shaders:start (generated by demo/tools/sync_shaders.py) ---
const BACKGROUND_VERTEX_SHADER = `#version 410 core

out vec2 vUV;

void main()
{
	// Attributeless. A triangle strip of four gives the corners in the order
	// (-1,-1) (1,-1) (-1,1) (1,1), which is what the bit tests below produce.
	vec2 c = vec2( ( gl_VertexID & 1 ) == 0 ? -1.0 : 1.0,
	               ( gl_VertexID & 2 ) == 0 ? -1.0 : 1.0 );

	vUV         = c * 0.5 + 0.5;
	gl_Position = vec4( c, 0.0, 1.0 );
}
`;

const BACKGROUND_FRAGMENT_SHADER = `#version 410 core

in vec2 vUV;

uniform vec4 BackColour;

#ifdef SHUNT_EFFECT
uniform sampler2D Clip;
uniform vec2 MaxUV;

// How much of the clip to lay down behind the shapes. 1 for the modes that draw
// over the clip; 1 - Mix for Reveal and Colourise, which build their picture
// only where the shapes are and so have to fade the untouched clip back IN as
// the effect is mixed OUT. At Mix = 1 this is 0 and the background pass clears
// to transparent.
uniform float ClipGain;
#endif

out vec4 fragColor;

void main()
{
#ifdef SHUNT_EFFECT
	// The clip arrives premultiplied and leaves the same way, so scaling both
	// its colour and its alpha by one gain is the whole of the fade.
	fragColor = texture( Clip, vUV * MaxUV ) * ClipGain;
#else
	fragColor = vec4( BackColour.rgb * BackColour.a, BackColour.a );
#endif
}
`;

const SHAPE_VERTEX_SHADER = `#version 410 core

uniform vec4 Xform[ 64 ];   // centre.xy in frame space, radius, rotation
uniform vec4 Tint[ 64 ];    // rgb, alpha
uniform vec4 Cell[ 64 ];    // the shape's image rectangle: u0, v0, u1, v1
uniform vec2 Resolution;
uniform float Bound;
uniform float Stretch;

// Drop shadows ride in the same instanced draw as the shapes they belong to.
// With ShadowPass on there are TWO instances per shape -- its shadow, then the
// shape -- so each shadow is drawn after every older shape and before its own:
// it falls on the shapes it has slid over and never on itself. Two draws, all
// shadows then all shapes, would put every shadow under every shape and the
// overlap the whole plugin is about would lose its depth.
uniform int ShadowPass;
uniform vec2 ShadowOffset;  // in shape radii, on SCREEN, y down
uniform float ShadowBlur;   // in shape radii

out vec2 vLocal;
out vec4 vTint;
out vec2 vClipUV;
out vec4 vCell;
out float vShadow;
out float vRotation;

void main()
{
	vec2 c = vec2( ( gl_VertexID & 1 ) == 0 ? -1.0 : 1.0,
	               ( gl_VertexID & 2 ) == 0 ? -1.0 : 1.0 );

	int index    = gl_InstanceID;
	float shadow = 0.0;
	if( ShadowPass == 1 )
	{
		index  = gl_InstanceID / 2;
		shadow = ( gl_InstanceID % 2 ) == 0 ? 1.0 : 0.0;
	}

	vec4 xf   = Xform[ index ];
	vTint     = Tint[ index ];
	vCell     = Cell[ index ];
	vShadow   = shadow;
	vRotation = xf.w;

	// Shape space: the primitive has unit radius and Stretch widens it on x.
	// The quad has to cover the stretched, rounded, outlined, feathered shape,
	// which is what Bound already accounts for -- and a shadow's blur on top.
	float reach = Bound + shadow * ShadowBlur;
	vec2 local  = c * vec2( reach * Stretch, reach );
	vLocal      = local;

	float ca     = cos( xf.w );
	float sa     = sin( xf.w );
	vec2 rotated = vec2( local.x * ca - local.y * sa,
	                     local.x * sa + local.y * ca );

	// The radius is a fraction of the SHORT edge, expressed here as a fraction
	// of each axis so that a circle comes out round on a 16:9 output. The train
	// runs in frame space and shapes are sized in short-edge fractions; those
	// are the same number only on a square render, which is exactly why this
	// looks correct in a 1:1 test and turns into ellipses on a real output if it
	// is dropped.
	vec2 shortEdge = ( Resolution.x >= Resolution.y )
	                 ? vec2( Resolution.y / Resolution.x, 1.0 )
	                 : vec2( 1.0, Resolution.x / Resolution.y );

	// The shadow's offset is added AFTER the rotation: the light is fixed on
	// the screen, so a shape turning does not swing its shadow round with it.
	vec2 framePos = xf.xy + ( rotated + shadow * ShadowOffset ) * xf.z * shortEdge;

	// The clip UV is carried from here rather than recovered from gl_FragCoord
	// in the fragment shader, because gl_FragCoord is in window coordinates and
	// includes the host's viewport offset, which is not always zero.
	vClipUV = vec2( framePos.x, 1.0 - framePos.y );

	// Frame space (0..1, y down) to clip space (-1..1, y up).
	gl_Position = vec4( framePos.x * 2.0 - 1.0, 1.0 - framePos.y * 2.0, 0.0, 1.0 );
}
`;

const SHAPE_FRAGMENT_SHADER = `#version 410 core

in vec2 vLocal;
in vec4 vTint;
in vec2 vClipUV;
in vec4 vCell;
in float vShadow;
in float vRotation;

uniform int ShapeKind;
uniform float Stretch;
uniform float Roundness;
uniform float Outline;
uniform float Softness;
uniform float Shade;
uniform float LightAngle;
uniform int SampleMode;

// The picture on the shapes. One texture whatever it came from -- a file, a
// folder packed into a grid, a sprite sheet -- and a rectangle per shape in
// vCell. Straight alpha.
uniform sampler2D Imagery;
uniform int HasImage;
uniform float ImageMix;

// The entry side's rotation, in radians. The image turns with Angle but not
// with the side the train comes in from: shape space is rotated to face the
// direction of travel, and a picture of a face should not lie on its side
// because the train now falls from the top.
uniform float SideTurn;

uniform float ShadowAmount;
uniform float ShadowBlur;

// 0: the shapes' own colours. 1: white, for a matte. 2: black, for an inverse
// matte. Coverage, opacity and the image's alpha all still apply -- only the
// colour is replaced -- so a soft edge is a soft edge in the matte too.
uniform int Matte;

#ifdef SHUNT_EFFECT
uniform sampler2D Clip;
uniform vec2 MaxUV;
#endif

out vec4 fragColor;

//---------------------------------------------------------------------------
// Distance functions. All normalised so the shape's furthest point sits at
// radius 1, which is what lets one Bound and one outline width serve all eight.
// The bodies are the standard analytic forms (Inigo Quilez's 2D distance
// function derivations); the normalisation constants are ours.
//---------------------------------------------------------------------------
float sdCircle( vec2 p )
{
	return length( p ) - 1.0;
}

float sdBox( vec2 p, vec2 b )
{
	vec2 q = abs( p ) - b;
	return min( max( q.x, q.y ), 0.0 ) + length( max( q, 0.0 ) );
}

float sdTriangle( vec2 p )
{
	const float k = 1.7320508;   // sqrt(3)
	const float s = 1.1547005;   // 2/sqrt(3): pulls the apex from 2/sqrt(3) to 1

	// Shape space runs y-down to match frame space, and the analytic form is
	// written y-up, so the flip here is what makes the triangle point up on
	// screen rather than down.
	p = vec2( p.x, -p.y ) * s;

	p.x = abs( p.x ) - 1.0;
	p.y = p.y + 1.0 / k;
	if( p.x + k * p.y > 0.0 )
		p = vec2( p.x - k * p.y, -k * p.x - p.y ) * 0.5;
	p.x -= clamp( p.x, -2.0, 0.0 );

	return -length( p ) * sign( p.y ) / s;
}

float sdHexagon( vec2 p )
{
	const vec3 k  = vec3( -0.8660254, 0.5, 0.5773503 );
	const float r = 0.8660254;   // apothem, giving a circumradius of 1

	p = abs( p );
	p -= 2.0 * min( dot( k.xy, p ), 0.0 ) * k.xy;
	p -= vec2( clamp( p.x, -k.z * r, k.z * r ), r );

	return length( p ) * sign( p.y );
}

float sdStar5( vec2 p, float rf )
{
	const vec2 k1 = vec2( 0.809016994, -0.587785252 );
	const vec2 k2 = vec2( -k1.x, k1.y );

	p = vec2( p.x, -p.y );   // point up on screen, as for the triangle

	p.x = abs( p.x );
	p -= 2.0 * max( dot( k1, p ), 0.0 ) * k1;
	p -= 2.0 * max( dot( k2, p ), 0.0 ) * k2;
	p.x = abs( p.x );
	p.y -= 1.0;

	vec2 ba = rf * vec2( -k1.y, k1.x ) - vec2( 0.0, 1.0 );
	float h = clamp( dot( p, ba ) / dot( ba, ba ), 0.0, 1.0 );

	// Negated: this construction is the one shape here whose analytic form comes
	// out POSITIVE inside, and every caller and every downstream step -- the
	// outline's abs(), the feather's smoothstep, the coverage -- assumes
	// negative inside. Left as it stood, the star renders as a solid quad with a
	// star-shaped hole in it, which is a striking picture and entirely wrong.
	return -length( p - ba * h ) * sign( h * ba.x - p.x );
}

float sdCross( vec2 p, vec2 b )
{
	p = abs( p );
	p = ( p.y > p.x ) ? p.yx : p.xy;

	vec2 q  = p - b;
	float k = max( q.y, q.x );
	vec2 w  = ( k > 0.0 ) ? q : vec2( b.y - p.x, -k );

	return sign( k ) * length( max( w, 0.0 ) );
}

float sdRing( vec2 p, float thickness )
{
	// Ring is the one shape where Roundness means thickness rather than corner
	// rounding: a circle has no corners to round, so the slider would otherwise
	// be dead here, and a ring whose weight cannot be set is not much of a ring.
	float t = clamp( thickness, 0.02, 0.9 );
	return abs( length( p ) - ( 1.0 - t * 0.5 ) ) - t * 0.5;
}

float shapeDistance( vec2 p )
{
	// Generic corner rounding: shrink the shape, then dilate the field back out
	// by the same amount. Shrink-then-dilate rather than dilate alone, so the
	// outer extent stays where Bound was told it would be -- a shape that grew
	// past its own quad loses a corner, and a lost corner on a rotated square
	// reads as the shape wobbling rather than as a bounds bug.
	float rr = ( ShapeKind == 6 ) ? 0.0 : clamp( Roundness, 0.0, 1.0 ) * 0.35;
	float k  = 1.0 - rr;

	vec2 q = p / k;
	float d;

	if( ShapeKind == 0 )      d = sdCircle( q );
	else if( ShapeKind == 1 ) d = sdBox( q, vec2( 1.0 ) );
	else if( ShapeKind == 2 ) d = sdTriangle( q );
	else if( ShapeKind == 3 ) d = sdHexagon( q );
	else if( ShapeKind == 4 ) d = sdStar5( q, 0.45 );
	else if( ShapeKind == 5 ) d = sdCross( q, vec2( 1.0, 0.3 ) );
	else if( ShapeKind == 6 ) d = sdRing( q, Roundness );
	else                      d = sdBox( q, vec2( 1.0, 0.15 ) );

	return d * k - rr;
}

void main()
{
	// Undo the stretch to evaluate the primitive, then scale the field by the
	// smaller axis so the result never OVERstates the distance. A conservative
	// field keeps the outline and the feather inside the quad; an optimistic
	// one would let them spill past its edge and get cut off square.
	vec2 st = vec2( Stretch, 1.0 );
	float d0 = shapeDistance( vLocal / st ) * min( st.x, st.y );

	// The antialiasing width is taken from the distance BEFORE the outline's
	// abs(). abs() creases the field at d == 0, which is the centre line of the
	// stroke, and fwidth() of a crease spikes -- giving a dark seam down the
	// middle of every outline. Sampling the width from the smooth field costs
	// nothing and removes the artefact entirely.
	float aa = fwidth( d0 );

	float d = ( Outline > 0.001 ) ? abs( d0 ) - Outline * 0.5 : d0;

	bool isShadow = vShadow > 0.5;

	// A shadow is the same silhouette with a wider feather: the blur spreads it
	// by ShadowBlur either side of the edge, which is what the quad was grown
	// by in the vertex shader.
	float feather  = isShadow ? max( max( aa, Softness * 2.0 ), ShadowBlur * 2.0 )
	                          : max( aa, Softness * 2.0 );
	float coverage = 1.0 - smoothstep( -feather * 0.5, feather * 0.5, d );

	if( coverage <= 0.0 )
		discard;

	//-----------------------------------------------------------------------
	// The picture. Shape space is y-down with unit radius, so the square
	// (-1..1) maps onto the cell with its top row at the top of the shape.
	// Clamped to the cell, because the quad is bigger than the square -- for
	// the rounding, the outline and the feather -- and past its edge the cell
	// has neighbours.
	//-----------------------------------------------------------------------
	vec4 image = vec4( 1.0 );
	if( HasImage == 1 )
	{
		vec2 p   = vLocal / st;
		float cs = cos( SideTurn );
		float sn = sin( SideTurn );
		vec2 q   = vec2( p.x * cs - p.y * sn, p.x * sn + p.y * cs );
		vec2 t   = clamp( q * 0.5 + 0.5, 0.0, 1.0 );
		image    = texture( Imagery, mix( vCell.xy, vCell.zw, t ) );
	}

	float imageAlpha = ( HasImage == 1 ) ? mix( 1.0, image.a, ImageMix ) : 1.0;

	if( isShadow )
	{
		// Black, at the shape's own opacity and the picture's alpha, so a sprite
		// with a transparent surround casts the sprite's shadow and not the
		// square's.
		float shadowAlpha = coverage * vTint.a * imageAlpha * ShadowAmount;
		if( shadowAlpha <= 0.0 )
			discard;
		fragColor = vec4( 0.0, 0.0, 0.0, shadowAlpha );
		return;
	}

	vec3 rgb    = vTint.rgb;
	float alpha = coverage * vTint.a * imageAlpha;

	if( HasImage == 1 )
		rgb = mix( vTint.rgb, image.rgb * vTint.rgb, ImageMix );

#ifdef SHUNT_EFFECT
	// 1 = Reveal (the clip, cut to the shapes), 2 = Colourise (the clip tinted).
	// 0 = Over and 3 = Hide both leave the colour alone: Over draws the shape's
	// own colour, and Hide's colour is discarded by the blend function, which
	// uses only the alpha.
	if( SampleMode == 1 || SampleMode == 2 )
	{
		vec4 clip     = texture( Clip, vClipUV * MaxUV );
		vec3 clipRGB  = clip.a > 0.0 ? clip.rgb / clip.a : vec3( 0.0 );

		rgb   = ( SampleMode == 2 ) ? clipRGB * vTint.rgb : clipRGB;
		alpha = alpha * clip.a;
	}
#endif

	//-----------------------------------------------------------------------
	// Shading. Light the flat shape as though it had been inflated.
	//
	// The distance field already knows everything needed for a normal: how far
	// inside the shape a pixel is, and -- through its gradient -- which way the
	// nearest edge lies. In-plane at the rim, facing the viewer in the middle.
	// For a circle that construction IS the sphere normal exactly; every other
	// primitive gets the same treatment and reads as a pillow rather than a
	// ball, because a pillow is what its field actually describes.
	//
	// It earns its place here more than it did in orrery: a train of shading
	// segments sliding over one another is what makes the overlap read as depth
	// rather than as two flat shapes on top of each other.
	//-----------------------------------------------------------------------
	if( Matte == 1 )
		rgb = vec3( 1.0 );
	else if( Matte == 2 )
		rgb = vec3( 0.0 );

	if( Shade > 0.001 && Matte == 0 )
	{
		// Central differences rather than fwidth: a screen-space derivative is
		// one value per 2x2 quad, and these shapes are deliberately small, so
		// the facets would be plainly visible.
		const float h = 0.01;
		float gx = shapeDistance( vec2( vLocal.x + h, vLocal.y ) / st )
		         - shapeDistance( vec2( vLocal.x - h, vLocal.y ) / st );
		float gy = shapeDistance( vec2( vLocal.x, vLocal.y + h ) / st )
		         - shapeDistance( vec2( vLocal.x, vLocal.y - h ) / st );

		vec2 g       = vec2( gx, gy );
		float glen   = length( g );
		vec2 outward = ( glen > 1e-6 ) ? g / glen : vec2( 0.0 );

		// 1 at the rim, 0 at the deepest point inside. The reach is the shape's
		// own unit radius carried through the stretch, so a squashed shape
		// inflates by as much as it is wide rather than always by the same
		// amount.
		float reach = max( min( st.x, st.y ), 1e-4 );
		float s     = clamp( 1.0 + d0 / reach, 0.0, 1.0 );

		vec3 normal = vec3( outward * s, sqrt( max( 0.0, 1.0 - s * s ) ) );

		// The light is fixed on the SCREEN, so it is turned back into shape
		// space by the shape's own rotation. Up to 0.1.0 it was not, and the
		// highlight swung round with Angle and with the entry side -- a train
		// falling from the top was lit from the side -- which a drop shadow cast
		// from the same Light control would have made obvious.
		//
		// The y flip is because shape space runs y-down to match frame space:
		// without it, raising the Light control walks the highlight the wrong
		// way round the shape.
		float a      = LightAngle * 6.28318531;
		vec2 screenL = vec2( cos( a ), -sin( a ) );
		float cr     = cos( vRotation );
		float sr     = sin( vRotation );
		vec2 localL  = vec2( screenL.x * cr + screenL.y * sr,
		                     -screenL.x * sr + screenL.y * cr );
		vec3 toLight = normalize( vec3( localL, 0.65 ) );

		float lambert = max( dot( normal, toLight ), 0.0 );
		// Not \`half\`: that is a reserved word in GLSL and the compiler's
		// message about it is not a helpful one.
		vec3 halfway  = normalize( toLight + vec3( 0.0, 0.0, 1.0 ) );
		float spec    = pow( max( dot( normal, halfway ), 0.0 ), 24.0 );

		// The ambient term is not politeness: these shapes are frequently the
		// source for a pixel map, and a fixture that goes to black on the far
		// side of the light reads as a dead channel rather than as shading.
		vec3 lit = rgb * ( 0.35 + 0.75 * lambert ) + vec3( 0.5 * spec );

		rgb = mix( rgb, lit, clamp( Shade, 0.0, 1.0 ) );
	}

	fragColor = vec4( rgb * alpha, alpha );
}
`;

// --- shaders:end ---

const EFFECT_DEFINE = '#define SHUNT_EFFECT 1\n';

function withDefines(shader, defines) {
  if (!defines) return shader;
  const afterVersion = shader.indexOf('\n');
  if (afterVersion === -1) return shader;
  return shader.slice(0, afterVersion + 1) + defines + shader.slice(afterVersion + 1);
}

//===========================================================================
// Shapes.cpp
//===========================================================================

const SHAPE_NAMES = ['Circle', 'Square', 'Triangle', 'Hexagon', 'Star', 'Cross', 'Ring', 'Bar'];
const SIDE_NAMES = ['Left', 'Right', 'Top', 'Bottom'];
const GAP_UNIT_NAMES = ['Thickness', 'Pixels'];
const SYNC_NAMES = ['Free', 'Beat', 'Bar', 'Manual'];
const COLOUR_MODE_NAMES = ['White', 'Solid', 'Hue Spread', 'Hue Cycle'];
const BLEND_NAMES = ['Over', 'Add', 'Max'];
// One list for both bundles, because the panel's elements are fixed: the
// plugin declares Over / Reveal / Hide / Colourise on the effect and Over /
// Matte / Inverse Matte on the source, with the values lined up so that the
// same element means the corresponding thing in each. Colourise on the source
// clamps to Inverse Matte, exactly as a composition moved across would.
const MASK_MODE_NAMES = ['Over', 'Reveal · Matte', 'Hide · Inverse Matte', 'Colourise'];
const LANES_NAMES = ['Off', 'Step', 'Random'];
const IMAGE_NAMES = ['None', 'The clip'];
const IMAGE_SOURCE_NAMES = ['Single', 'Folder', 'Sprite Sheet'];
const IMAGE_PICK_NAMES = ['Same', 'Random', 'In Order'];
const MAX_GRID = 16;
const MAX_SPRITE = 255;

const MAX_SHAPES = 64;
const CLEARANCE = 0.02;

/** The padded extent that sizes the quad. Erring high costs overdraw; erring
 *  low silently cuts a corner off a rotated shape. */
function shapeBound(shape) {
  switch (shape) {
    case 0: case 4: case 6: return 1.0;   // Circle, Star, Ring
    case 1: return 1.4143;                // Square: corners at sqrt(2)
    case 2: return 1.0;                   // Triangle
    case 3: return 1.0;                   // Hexagon
    case 5: return 1.05;                  // Cross
    case 7: return 1.05;                  // Bar
    default: return 1.4143;
  }
}

/** The TRUE axis-aligned half extents, unpadded. This is what the Gap control
 *  means by "thickness", so padding here would open a visible space between two
 *  shapes the operator asked to have touching. */
function shapeHalfExtents(shape) {
  switch (shape) {
    case 0: case 6: return [1.0, 1.0];               // Circle, Ring
    case 1: case 5: return [1.0, 1.0];               // Square, Cross
    case 2: return [0.8660254, 0.75];                // Triangle: 1 up, 0.5 down
    case 3: return [1.0, 0.8660254];                 // Hexagon
    case 4: return [0.9510565, 0.9045085];           // Star
    case 7: return [1.0, 0.15];                      // Bar
    default: return [1.0, 1.0];
  }
}

//===========================================================================
// Controls.cpp — the 0..1 host values, and what they mean
//===========================================================================

const clamp01 = (v) => Math.min(1, Math.max(0, v));
const exponential = (v, lo, hi) => lo * (hi / lo) ** clamp01(v);

const countFromParam = (v) => 1 + Math.round(63 * clamp01(v) * clamp01(v));
const sizeFromParam = (v) => exponential(v, 0.005, 0.5);
const stretchFromParam = (v) => 10 ** (2 * clamp01(v) - 1);
const angleFromParam = (v) => clamp01(v);
const softnessFromParam = (v) => clamp01(v) * 0.5;
const travelFromParam = (v) => clamp01(v);
const gapFromParam = (v, pixels) => (pixels ? clamp01(v) * 512 : clamp01(v) * 4);
const dwellFromParam = (v) => clamp01(v) * 0.95;
const acrossFromParam = (v) => clamp01(v) * 1.5 - 0.25;
const hueSpreadFromParam = (v) => clamp01(v);
const laneStepFromParam = (v) => clamp01(v) - 0.5;
const shadowDistanceFromParam = (v) => clamp01(v);
const shadowBlurFromParam = (v) => clamp01(v);

// The plugin declares these three as FF_TYPE_INTEGER with real ranges; this
// page's kit only has 0..1 sliders, so it maps them and shows the integer.
const columnsFromParam = (v) => 1 + Math.round(clamp01(v) * (MAX_GRID - 1));
const spriteFromParam = (v) => Math.round(clamp01(v) * MAX_SPRITE);

function speedFromParam(value) {
  const v = clamp01(value);
  // A dead zone rather than a curve that merely approaches zero: "stopped" has
  // to be a place you can land on.
  if (v < 0.02) return 0;
  return exponential((v - 0.02) / 0.98, 0.01, 2.0);
}

//===========================================================================
// Queue.cpp — where every shape in the train is, at a given phase
//===========================================================================

const fract = (x) => x - Math.floor(x);
const travelsHorizontally = (side) => side === 0 || side === 1;

/** Short-edge radius to a fraction of each frame axis. Those are the same
 *  number only on a square output, and mixing them up is invisible at 1:1. */
function frameRadius(scale, aspect) {
  return aspect >= 1 ? [scale / aspect, scale] : [scale, scale * aspect];
}

/** The shape's rotation on screen: the direction of travel plus whatever Angle
 *  adds. Measuring Angle from the travel direction is what makes a Bar behave
 *  the same way whichever edge the train comes in from. */
const sideRotation = (side) => [0, Math.PI, Math.PI / 2, -Math.PI / 2][side] ?? 0;

function screenRotation(p) {
  return sideRotation(p.side) + p.angle * Math.PI * 2;
}

/** The rotated box's half extents on the frame's two axes, in frame-span units.
 *  The support function of a rotated box: rotation happens in shape space and
 *  the anisotropic frame scaling comes after it. */
function rotatedHalfExtents(p) {
  const [ex, ey] = shapeHalfExtents(p.shape);
  const hx = ex * Math.max(0, p.stretch);
  const hy = ey;

  const theta = screenRotation(p);
  const c = Math.abs(Math.cos(theta));
  const s = Math.abs(Math.sin(theta));

  const [rx, ry] = frameRadius(p.size, p.aspect);
  return [rx * (hx * c + hy * s), ry * (hx * s + hy * c)];
}

/** Half the shape's extent along the direction of travel. */
function halfThickness(p) {
  const [onX, onY] = rotatedHalfExtents(p);
  return travelsHorizontally(p.side) ? onX : onY;
}

/** Half the shape's extent ACROSS the direction of travel. */
function crossHalfThickness(p) {
  const [onX, onY] = rotatedHalfExtents(p);
  return travelsHorizontally(p.side) ? onY : onX;
}

/** splitmix64's finaliser, in BigInt so it is bit-for-bit the plugin's. A
 *  set's random lane is a pure function of its number. */
const MASK64 = (1n << 64n) - 1n;
function hash01(n) {
  let x = (BigInt.asUintN(64, BigInt(n)) + 0x9E3779B97F4A7C15n) & MASK64;
  x = ((x ^ (x >> 30n)) * 0xBF58476D1CE4E5B9n) & MASK64;
  x = ((x ^ (x >> 27n)) * 0x94D049BB133111EBn) & MASK64;
  x ^= x >> 31n;
  return Number(x >> 11n) / 9007199254740992;
}

/** The set a slot belongs to: every shape released in one cycle shares one. */
function setOf(p, slot) {
  const count = Math.max(1, p.count);
  return Math.floor(p.phase - slot / count);
}

/** Where set `set` runs on the cross axis. Off is Across; Step adds Lane Step
 *  per set; Random moves half the band plus a jitter small enough that two
 *  consecutive sets are never closer than one shape. Both wrap inside the band
 *  where a whole shape stays on the frame. */
function laneAcross(p, set) {
  if (p.lanes === 0) return p.across;

  const e = Math.min(0.45, crossHalfThickness(p));
  const band = 1 - 2 * e;
  const u0 = (p.across - e) / band;

  let u;
  if (p.lanes === 1) {
    u = fract(u0 + (set * p.laneStep) / band);
  } else {
    const sep = Math.min(1, (2 * e) / band);
    const jitter = Math.max(0, 0.5 - sep);
    u = fract(u0 + 0.5 * set + (hash01(set) - 0.5) * jitter);
  }
  return e + u * band;
}

/** Which cell a shape gets, by its release number. Same as PickCell, including
 *  the second hash stream, so a Random pick here is the plugin's pick. */
function pickCell(pick, release, sprite, cellCount) {
  if (cellCount <= 0) return 0;
  let index;
  if (pick === 1) {
    let x = (BigInt.asUintN(64, BigInt(release)) * 0xD1B54A32D192ED03n + 0x632BE59BD9B4E019n) & MASK64;
    x = ((x ^ (x >> 30n)) * 0xBF58476D1CE4E5B9n) & MASK64;
    x = ((x ^ (x >> 27n)) * 0x94D049BB133111EBn) & MASK64;
    x ^= x >> 31n;
    index = Number(x % BigInt(cellCount));
  } else if (pick === 2) {
    index = release + sprite;
  } else {
    index = sprite;
  }
  return ((index % cellCount) + cellCount) % cellCount;
}

/** Centre-to-centre spacing between standing shapes, in frame-span units. At
 *  one thickness they stand edge to edge; below it they overlap. */
function gapSpan(p) {
  if (p.gapUnits === 1) {
    const span = Math.max(1, p.spanPixels);
    return Math.max(0, p.gapValue) / span;
  }
  return Math.max(0, p.gapValue) * 2 * halfThickness(p);
}

const margin = (p) => halfThickness(p) + CLEARANCE;

/** Derived, not a control. This is the whole trick: it makes every shape's run
 *  exactly one cycle long whatever its slot. */
function slideSpeed(p) {
  const idle = Math.max(0.02, 1 - clamp01(p.dwell));
  return (1 + 2 * margin(p)) / idle;
}

/** Clamped so a queue longer than the run backs up off-stage rather than trying
 *  to stand behind its own starting point. */
function slotDepth(p, slot) {
  return Math.max(-margin(p), p.travel - slot * gapSpan(p));
}

/** Slot 0 leads. Slot k was released k/count of a cycle later. */
function slotAge(p, slot) {
  return fract(p.phase - slot / Math.max(1, p.count));
}

function hsvToRgb(h, s, v) {
  h = fract(h) * 6;
  s = clamp01(s);
  v = clamp01(v);

  const sector = Math.floor(h) % 6;
  const f = h - Math.floor(h);
  const p = v * (1 - s);
  const q = v * (1 - s * f);
  const t = v * (1 - s * (1 - f));

  switch (sector) {
    case 0: return [v, t, p];
    case 1: return [q, v, p];
    case 2: return [p, v, t];
    case 3: return [p, q, v];
    case 4: return [t, p, v];
    default: return [v, p, q];
  }
}

function rgbToHsv(r, g, b) {
  const maxC = Math.max(r, g, b);
  const minC = Math.min(r, g, b);
  const d = maxC - minC;

  const v = maxC;
  const s = maxC > 0 ? d / maxC : 0;
  if (d <= 0) return [0, s, v];

  let h;
  if (maxC === r) h = (g - b) / d + (g < b ? 6 : 0);
  else if (maxC === g) h = (b - r) / d + 2;
  else h = (r - g) / d + 4;

  return [h / 6, s, v];
}

/** One shape, by slot. In, stand, out: three straight lines and two thresholds,
 *  which is the whole of the motion. */
function solveSlot(p, slot) {
  const count = Math.max(1, p.count);

  const m = margin(p);
  const v = slideSpeed(p);
  const park = slotDepth(p, slot);
  const dwell = clamp01(p.dwell);
  const age = slotAge(p, slot);

  const set = setOf(p, slot);
  const across = laneAcross(p, set);

  const arrive = (park + m) / v;

  let depth = park;
  let standing = false;

  if (age < arrive) depth = -m + v * age;
  else if (age < arrive + dwell) standing = true;
  else depth = park + v * (age - arrive - dwell);

  // Depth and cross-position to frame space. y runs DOWN, so Top enters at
  // y = 0 and travels towards 1.
  let x;
  let y;
  if (p.side === 0) { x = depth; y = across; }
  else if (p.side === 1) { x = 1 - depth; y = across; }
  else if (p.side === 2) { x = across; y = depth; }
  else { x = across; y = 1 - depth; }

  // Colour is keyed off the SLOT, not the draw order, so a hue spread reads as
  // a stable pattern marching through rather than the whole set flickering
  // every time the queue turns over.
  let r = 1;
  let g = 1;
  let b = 1;

  if (p.colourMode === 1) {
    r = p.r; g = p.g; b = p.b;
  } else if (p.colourMode === 2 || p.colourMode === 3) {
    let [h, s, val] = rgbToHsv(p.r, p.g, p.b);
    // White has no hue and no saturation, so a straight reading of the default
    // swatch would give a train of identical white shapes and look broken.
    if (s < 0.01) {
      s = 1;
      if (val < 0.01) val = 1;
    }
    const along = count > 1 ? slot / count : 0;
    let hue = h + p.hueSpread * along;
    if (p.colourMode === 3) hue += p.phase;
    [r, g, b] = hsvToRgb(hue, s, val);
  }

  return {
    x,
    y,
    scale: Math.max(0, p.size),
    rotation: screenRotation(p),
    r,
    g,
    b,
    a: clamp01(p.opacity),
    slot,
    age,
    depth,
    standing,
    set,
    release: set * count + slot,
  };
}

/** Every shape, in DRAW order: oldest first, newest last.
 *
 *  "The leading edge of #2 slides over the trailing edge of #1" is the whole
 *  reason this sort is here. The order rotates once per release, because which
 *  slot is newest turns over as the phase advances — a fixed order would put
 *  the same shape on top for ever and look wrong for most of every cycle. */
function solve(p) {
  const count = Math.min(MAX_SHAPES, Math.max(1, p.count));
  const out = [];
  for (let slot = 0; slot < count; slot += 1) out.push(solveSlot(p, slot));
  out.sort((a, b) => b.age - a.age);
  return out;
}

//===========================================================================
// Presets.h
//===========================================================================

const PRESET_PARAM_IDS = [
  'shape', 'size', 'stretch', 'angle', 'roundness', 'outline', 'softness',
  'side', 'count', 'travel', 'gap', 'dwell', 'speed',
  'colourMode', 'shapeR', 'shapeG', 'shapeB', 'hueSpread', 'opacity',
  'backR', 'backG', 'backB', 'backOpacity', 'blend', 'shade',
];

const PRESET_TABLE = [
  ['Caterpillar', [0, 0.62, 0.5, 0.0, 0.0, 0.0, 0.0, 0, 0.333, 0.78, 0.1875, 0.55, 0.574,
    0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0.0]],
  ['Conveyor', [1, 0.46, 0.5, 0.0, 0.25, 0.0, 0.0, 0, 0.29, 0.85, 0.32, 0.18, 0.6,
    0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 2, 0.0]],
  ['Stacking Up', [0, 0.46, 0.5, 0.0, 0.0, 0.0, 0.0, 1, 0.408, 0.9, 0.24, 0.85, 0.5,
    2, 1, 1, 1, 0.7, 1, 0, 0, 0, 1, 0, 0.6]],
  ['Ladder Fall', [7, 0.62, 0.5, 0.25, 0.4, 0.0, 0.06, 2, 0.29, 0.92, 0.3, 0.62, 0.52,
    0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 2, 0.0]],
  ['Ticker', [7, 0.34, 0.62, 0.0, 0.0, 0.0, 0.0, 1, 0.56, 1.0, 0.33, 0.1, 0.66,
    3, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0.0]],
  ['Shingle', [0, 0.66, 0.5, 0.0, 0.0, 0.0, 0.0, 0, 0.25, 0.78, 0.1, 0.55, 0.5,
    2, 0.2, 0.6, 1.0, 0.35, 1, 0, 0, 0, 1, 0, 1.0]],
  ['Bullseye', [6, 0.66, 0.5, 0.0, 0.7, 0.35, 0.0, 0, 0.315, 0.8, 0.15, 0.55, 0.55,
    1, 0.35, 0.85, 0.25, 1, 1, 0, 0, 0, 1, 0, 0.6]],
];

const PRESETS = Object.fromEntries(
  PRESET_TABLE.map(([name, values]) => [
    name,
    Object.fromEntries(values.map((value, i) => [PRESET_PARAM_IDS[i], value])),
  ]),
);

//===========================================================================
// The renderer. Two passes, no framebuffer.
//===========================================================================

class ShuntRenderer {
  constructor(gl) {
    this.gl = gl;

    // Both variants, compiled up front, because the picker switches between them
    // without a page reload.
    this.programs = {
      source: {
        background: new Program(gl, BACKGROUND_VERTEX_SHADER, BACKGROUND_FRAGMENT_SHADER, 'background'),
        shape: new Program(gl, SHAPE_VERTEX_SHADER, SHAPE_FRAGMENT_SHADER, 'shape'),
      },
      effect: {
        background: new Program(
          gl,
          BACKGROUND_VERTEX_SHADER,
          withDefines(BACKGROUND_FRAGMENT_SHADER, EFFECT_DEFINE),
          'background (effect)',
        ),
        shape: new Program(
          gl,
          SHAPE_VERTEX_SHADER,
          withDefines(SHAPE_FRAGMENT_SHADER, EFFECT_DEFINE),
          'shape (effect)',
        ),
      },
    };

    // A core profile refuses to draw with no vertex array bound, even though
    // both shaders build their geometry from gl_VertexID and source nothing.
    this.emptyVAO = gl.createVertexArray();

    this.xform = new Float32Array(MAX_SHAPES * 4);
    this.tint = new Float32Array(MAX_SHAPES * 4);
    this.cell = new Float32Array(MAX_SHAPES * 4);

    // One white texel for the Imagery sampler while no image is chosen, as
    // the plugin does: a sampler on texture 0 is "unloadable" to some drivers.
    this.placeholder = gl.createTexture();
    gl.bindTexture(gl.TEXTURE_2D, this.placeholder);
    gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA8, 1, 1, 0, gl.RGBA, gl.UNSIGNED_BYTE,
      new Uint8Array([255, 255, 255, 255]));
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.NEAREST);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.NEAREST);
    gl.bindTexture(gl.TEXTURE_2D, null);
  }

  /** The source's reading of Mask Mode: 0 Over, 1 Matte, 2 Inverse Matte. */
  sourceOutput(params, isEffect) {
    return isEffect ? 0 : Math.min(2, params.option('maskMode'));
  }

  /** The blend actually used: a matte is Over whatever Blend says. */
  blendUsed(params, isEffect) {
    return this.sourceOutput(params, isEffect) !== 0 ? 0 : params.option('blend');
  }

  /** The source fades through the constant blend factor except under Max,
   *  which ignores factors. See ApplyBlend in Shunt.cpp. */
  sourceFadesInBlend(params, isEffect) {
    return !isEffect && this.blendUsed(params, isEffect) !== 2;
  }

  /**
   * Free multiplies the clock by the rate — the phase is absolute rather than
   * integrated, which is what makes any frame renderable on its own. Manual
   * ignores Speed entirely: that mode is for driving Phase from a keyframe or a
   * MIDI fader, and a second clock underneath would fight whatever is driving it.
   */
  phaseAt(params, time) {
    const sync = params.option('sync');
    const speed = speedFromParam(params.get('speed'));
    const manual = params.get('phase');

    let driven = 0;
    if (sync === 0) {
      driven = time * speed;
    } else if (sync === 1 || sync === 2) {
      // This page has no transport, so it generates one at 120 BPM — the tempo
      // the plugin falls back to when a host reports none.
      const barSeconds = 240 / 120;
      const bars = time / barSeconds;
      driven = (sync === 1 ? bars * 4 : bars) * speed;
    }

    return driven + manual;
  }

  queueFrom(params, width, height, time, isEffect) {
    const side = params.option('side');
    const gapUnits = params.option('gapUnits');

    return {
      shape: params.option('shape'),
      side,
      count: countFromParam(params.get('count')),
      phase: this.phaseAt(params, time),

      travel: travelFromParam(params.get('travel')),
      dwell: dwellFromParam(params.get('dwell')),
      across: acrossFromParam(params.get('across')),

      lanes: params.option('lanes'),
      laneStep: laneStepFromParam(params.get('laneStep')),

      gapUnits,
      gapValue: gapFromParam(params.get('gap'), gapUnits === 1),
      // The pixel span is the raster's own count on the axis the train runs
      // along, so "40 pixels" means forty pixels of output whichever edge it
      // comes in from.
      spanPixels: travelsHorizontally(side) ? Math.max(1, width) : Math.max(1, height),

      size: sizeFromParam(params.get('size')),
      stretch: stretchFromParam(params.get('stretch')),
      angle: angleFromParam(params.get('angle')),

      colourMode: params.option('colourMode'),
      r: clamp01(params.get('shapeR')),
      g: clamp01(params.get('shapeG')),
      b: clamp01(params.get('shapeB')),
      hueSpread: hueSpreadFromParam(params.get('hueSpread')),

      // Mix fades the shape layer against the clip in the effect. In the source
      // it fades the whole output, through the blend's constant factor rather
      // than the alpha except under Max — see sourceFadesInBlend.
      opacity: clamp01(params.get('opacity'))
        * (this.sourceFadesInBlend(params, isEffect) ? 1 : clamp01(params.get('mix'))),

      aspect: width > 0 && height > 0 ? width / height : 1,
    };
  }

  applyBlend(blend, fade) {
    const gl = this.gl;
    gl.enable(gl.BLEND);
    gl.blendColor(0, 0, 0, fade);

    if (blend === 1) {
      gl.blendEquation(gl.FUNC_ADD);
      gl.blendFunc(gl.CONSTANT_ALPHA, gl.ONE);
    } else if (blend === 2) {
      // MAX ignores the factors entirely and takes the channel-wise maximum of
      // source and destination. That is what a mask wants — and it also throws
      // the draw order away, because max is commutative, so there is no "newest
      // on top" under it. The right trade for a mask, the wrong one for a
      // caterpillar, which is why Over is the default.
      gl.blendEquation(gl.MAX);
      gl.blendFunc(gl.ONE, gl.ONE);
    } else {
      // Premultiplied over, matching the shader's output. Draw order decides
      // what is on top, and solve() sorts newest last for exactly that reason.
      gl.blendEquation(gl.FUNC_ADD);
      gl.blendFunc(gl.CONSTANT_ALPHA, gl.ONE_MINUS_SRC_ALPHA);
    }
  }

  render({ input, params, width, height, time, variant }) {
    const gl = this.gl;
    const isEffect = variant === 'effect';
    const programs = isEffect ? this.programs.effect : this.programs.source;

    const queue = this.queueFrom(params, width, height, time, isEffect);
    const wagons = solve(queue);
    const count = wagons.length;

    const mask = isEffect ? params.option('maskMode') : 0;
    const output = this.sourceOutput(params, isEffect);
    const matte = output !== 0;
    const blend = this.blendUsed(params, isEffect);
    const mix01 = clamp01(params.get('mix'));
    const fade = this.sourceFadesInBlend(params, isEffect) ? mix01 : 1;

    // Shadows: not in Hide, whose blend would punch them out as holes, and not
    // in a matte.
    const shadowAmount = clamp01(params.get('shadow'));
    const shadows = shadowAmount > 0.001 && !matte && mask !== 2;

    // The plugin's Image is a file parameter. A page cannot read a path off
    // the visitor's disk, so here the clip picker's picture stands in for the
    // chosen file — a sheet, if you pick one of your own and say Sprite Sheet.
    // Folder has no stand-in and behaves as Single.
    const hasImage = params.option('image') === 1 && !!input?.texture;
    const imageSource = params.option('imageSource');
    let cells = [[0, 0, 1, 1]];
    if (hasImage && imageSource === 2) {
      const cols = columnsFromParam(params.get('columns'));
      const rows = columnsFromParam(params.get('rows'));
      cells = [];
      for (let j = 0; j < rows; j += 1) {
        for (let i = 0; i < cols; i += 1) cells.push([i / cols, j / rows, (i + 1) / cols, (j + 1) / rows]);
      }
    }

    // Reveal and Colourise build their picture only where the shapes are, so the
    // clip behind them fades IN as the effect mixes OUT.
    const buildsFromClip = mask === 1 || mask === 3;
    const clipGain = buildsFromClip ? 1 - mix01 : 1;

    const sampleMode = mask === 1 ? 1 : mask === 3 ? 2 : mask === 2 ? 3 : 0;

    gl.bindVertexArray(this.emptyVAO);

    //---------------------------------------------------------------------
    // Pass 1: the background.
    //---------------------------------------------------------------------
    gl.disable(gl.BLEND);
    const background = programs.background.use();

    if (isEffect) {
      bindTexture(gl, 0, input.texture);
      background.setSampler('Clip', 0);
      // The kit hands over a texture the picture exactly fills, so MaxUV is the
      // whole of it. In Resolume it is whatever GetMaxGLTexCoords reports.
      background.set('MaxUV', 1, 1);
      background.set('ClipGain', clipGain);
    } else if (matte) {
      const level = output === 2 ? 1 : 0;
      background.set('BackColour', level, level, level, mix01);
    } else {
      background.set(
        'BackColour',
        clamp01(params.get('backR')),
        clamp01(params.get('backG')),
        clamp01(params.get('backB')),
        clamp01(params.get('backOpacity')) * mix01,
      );
    }

    gl.drawArrays(gl.TRIANGLE_STRIP, 0, 4);

    //---------------------------------------------------------------------
    // Pass 2: the shapes, in the order solve() put them — oldest first, so the
    // newest is drawn last and lands on top.
    //---------------------------------------------------------------------
    const shape = programs.shape.use();

    for (let i = 0; i < count; i += 1) {
      const w = wagons[i];
      const x = i * 4;
      this.xform[x + 0] = w.x;
      this.xform[x + 1] = w.y;
      this.xform[x + 2] = w.scale;
      this.xform[x + 3] = w.rotation;
      this.tint[x + 0] = w.r;
      this.tint[x + 1] = w.g;
      this.tint[x + 2] = w.b;
      this.tint[x + 3] = w.a;

      const c = cells[pickCell(params.option('imagePick'), w.release,
        spriteFromParam(params.get('sprite')), cells.length)];
      // The kit's clip texture is uploaded with v = 0 at the BOTTOM, as a
      // host's clip is; the plugin's own image upload puts the top row at
      // v = 0. Flip the rectangle here so the shader, which is the plugin's,
      // sees the top of the picture where it expects it.
      this.cell[x + 0] = c[0];
      this.cell[x + 1] = 1 - c[1];
      this.cell[x + 2] = c[2];
      this.cell[x + 3] = 1 - c[3];
    }

    shape.setArray('Xform', this.xform.subarray(0, count * 4), 4);
    shape.setArray('Tint', this.tint.subarray(0, count * 4), 4);
    shape.setArray('Cell', this.cell.subarray(0, count * 4), 4);

    const outline = clamp01(params.get('outline'));
    const softness = softnessFromParam(params.get('softness'));

    // The quad has to contain the shape, its outline, and its feather. Slack on
    // top because overdrawing a few pixels costs nothing and a shape that
    // reaches past its quad silently loses a corner.
    const bound = shapeBound(queue.shape) + outline * 0.5 + softness * 2 + 0.05;

    shape.set('Resolution', width, height);
    shape.set('Bound', bound);
    shape.set('Stretch', queue.stretch);
    shape.setInt('ShapeKind', queue.shape);
    shape.set('Roundness', clamp01(params.get('roundness')));
    shape.set('Outline', outline);
    shape.set('Softness', softness);
    shape.set('Shade', clamp01(params.get('shade')));
    shape.set('LightAngle', clamp01(params.get('light')));
    shape.setInt('SampleMode', sampleMode);
    shape.setInt('Matte', output);

    const lightTurn = clamp01(params.get('light')) * Math.PI * 2;
    const distance = shadowDistanceFromParam(params.get('shadowDistance'));
    shape.setInt('ShadowPass', shadows ? 1 : 0);
    shape.set('ShadowOffset', -Math.cos(lightTurn) * distance, Math.sin(lightTurn) * distance);
    shape.set('ShadowBlur', shadows ? shadowBlurFromParam(params.get('shadowBlur')) : 0);
    shape.set('ShadowAmount', shadowAmount);

    shape.setInt('HasImage', hasImage ? 1 : 0);
    shape.set('ImageMix', clamp01(params.get('imageMix')));
    shape.set('SideTurn', sideRotation(queue.side));
    bindTexture(gl, 1, hasImage ? input.texture : this.placeholder);
    shape.setSampler('Imagery', 1);
    gl.activeTexture(gl.TEXTURE0);

    if (isEffect) {
      bindTexture(gl, 0, input.texture);
      shape.setSampler('Clip', 0);
      shape.set('MaxUV', 1, 1);
    }

    if (mask === 2) {
      // Hide: punch the shapes out of what is already there — keep no source,
      // and scale the destination by the shape's transparency. This is the whole
      // of Hide, and it is why there is no mask buffer anywhere in this plugin.
      gl.enable(gl.BLEND);
      gl.blendEquation(gl.FUNC_ADD);
      gl.blendFunc(gl.ZERO, gl.ONE_MINUS_SRC_ALPHA);
    } else {
      this.applyBlend(blend, fade);
    }

    // Two instances per shape with shadows on — its shadow, then itself.
    gl.drawArraysInstanced(gl.TRIANGLE_STRIP, 0, 4, shadows ? count * 2 : count);
    bindTexture(gl, 1, null);
    gl.activeTexture(gl.TEXTURE0);

    //---------------------------------------------------------------------
    // Leave the state as the page is entitled to find it.
    //---------------------------------------------------------------------
    gl.disable(gl.BLEND);
    gl.blendEquation(gl.FUNC_ADD);
    gl.blendFunc(gl.ONE, gl.ONE_MINUS_SRC_ALPHA);
    gl.blendColor(0, 0, 0, 0);
    gl.bindVertexArray(null);
  }
}

//===========================================================================
// The page.
//===========================================================================

const pct = (v) => `${Math.round(v * 100)}%`;

mountDemo({
  name: 'Shunt',
  pluginId: 'SH01',
  tagline: 'Shapes slide in, bank up a set distance apart, stand, and are drawn away.',
  repo: 'https://github.com/stoatworks-labs/shunt',
  page: 'https://stoatworks-labs.com/software/shunt/',
  video: 'https://www.youtube.com/watch?v=m0wPwxjA5ls',
  showBackdrop: true,
  presets: PRESETS,

  // Which bundle. Shunt ships two, because FFGL resolves a single entry point
  // per binary: a source that draws over its own background, and a mask effect
  // that draws the same train over the clip or cuts it into it. They differ by a
  // constructor flag and a #define handed to the shader compiler.
  variants: {
    label: 'Plugin',
    default: 'source',
    options: [
      { id: 'source', name: 'Shunt', hint: 'The source: the train over its own background, on its own layer.' },
      { id: 'effect', name: 'Shunt Mask', hint: 'The effect: the same train over the clip, or cut into it.' },
    ],
  },

  sources: ['scene', 'grid', 'bars', 'ramp', 'spot', 'detail', 'alpha'],

  differences: [
    'The clip picker is the clip only in Shunt Mask. The source has no input at all — SetMinInputs is 0 — and draws over its own Background colour; here the picked clip also stands in for the Image, below.',
    'Image is a file parameter in the plugin, and a page cannot read a path from your disk, so the clip picker\'s picture — or one of your own — stands in for the chosen file. Folder, which loads every image beside the chosen one, has nothing to stand in for it and behaves as Single here.',
    'Columns, Rows and Sprite are integer parameters in the plugin, typed into as numbers. Here they are sliders that show the integer they land on.',
    'Beat and Bar lock to a 120 BPM transport generated in this page, which is the tempo the plugin falls back to when a host reports none. Resolume would supply its own, and the bar position with it. Manual ignores the clock entirely and is driven by the Phase slider, exactly as in the host.',
    'Preset is an option parameter in the plugin, with Custom as element 0 and a slider edit dropping back to it. Here the same seven presets are in the panel header instead, from the plugin\'s own table.',
    'Gap in Pixels counts pixels of THIS canvas, so changing the resolution picker changes how much of the frame a given number of pixels is — which is the point of the unit, and exactly what it does against a real pixel map.',
  ],

  params: [
    //---- Shape ------------------------------------------------------------
    {
      id: 'shape', name: 'Shape', type: 'option', default: 0, group: 'Shape',
      elements: SHAPE_NAMES,
      hint: 'Eight signed distance functions. An SDF is the right representation here because antialiasing is one smoothstep, outline is abs(d) − w, and softness is a wider smoothstep — one expression each, for all eight shapes.',
    },
    {
      id: 'size', name: 'Size', type: 'standard', default: 0.62, group: 'Shape',
      display: (v) => sizeFromParam(v).toFixed(3),
      hint: 'Radius as a fraction of the SHORT edge, which is what keeps a circle round on a 16:9 output. It also moves the Gap when Gap Units is Thickness, because a thickness is measured on the shape itself.',
    },
    {
      id: 'stretch', name: 'Stretch', type: 'standard', default: 0.5, group: 'Shape',
      display: (v) => `${stretchFromParam(v).toFixed(2)}×`,
      hint: 'Exactly 1.0 at the centre of the slider, because 2 × 0.5 − 1 is exactly 0 in binary floating point — which is the only reason a "1 at the centre" control can be trusted to reach 1.',
    },
    {
      id: 'angle', name: 'Angle', type: 'standard', default: 0.0, group: 'Shape',
      display: (v) => `${Math.round(angleFromParam(v) * 360)}°`,
      hint: 'Measured from the DIRECTION OF TRAVEL, not from the frame. So a Bar at 0 is a dash pointing the way it is going and at 90° it is a rung across the train — and changing which edge the train comes in from does not make you re-dial it.',
    },
    {
      id: 'roundness', name: 'Roundness', type: 'standard', default: 0.0, group: 'Shape',
      display: pct,
      hint: 'Shrink the shape, then dilate the field back out by the same amount, so the outer extent stays where Bound was told it would be. On Ring this is thickness instead — a circle has no corners to round.',
    },
    { id: 'outline', name: 'Outline', type: 'standard', default: 0.0, group: 'Shape', display: pct },
    {
      id: 'softness', name: 'Softness', type: 'standard', default: 0.0, group: 'Shape',
      display: (v) => softnessFromParam(v).toFixed(3),
      hint: 'Zero gives a hard edge on purpose: a feathered one means a fixture on the boundary reads a half-brightness colour that was never in the design.',
    },

    //---- Queue ------------------------------------------------------------
    {
      id: 'side', name: 'From', type: 'option', default: 0, group: 'Queue',
      elements: SIDE_NAMES,
      hint: 'Which edge the train comes in from. It travels away from that edge, and Travel, Gap in pixels and Angle are all measured along that direction.',
    },
    {
      id: 'count', name: 'Count', type: 'standard', default: 0.333, group: 'Queue',
      display: (v) => `${countFromParam(v)}`,
      hint: 'How many shapes are in the train. One is released every 1/Count of a cycle, and each one’s run is exactly one cycle long — so there are always exactly this many in play. Capped at 64 because the whole set goes up as two vec4 uniform arrays.',
    },
    {
      id: 'travel', name: 'Travel', type: 'standard', default: 0.78, group: 'Queue',
      display: pct,
      hint: 'How far in the HEAD of the queue goes, as a fraction of the frame’s span along the direction of travel. Everything else stands one Gap further back than the shape in front of it.',
    },
    {
      id: 'gapUnits', name: 'Gap Units', type: 'option', default: 0, group: 'Queue',
      elements: GAP_UNIT_NAMES,
      hint: 'Both, because both are the right answer to different jobs. A multiple of the shape’s own thickness keeps the train looking the same when Size changes; absolute pixels are what you need when the output is a pixel map and the spacing has to land on the fixture pitch.',
    },
    {
      id: 'gap', name: 'Gap', type: 'standard', default: 0.1875, group: 'Queue',
      // Both readings at once. The kit hands `display` the value and nothing
      // else, so it cannot see which unit is selected -- and showing both is
      // better anyway, because the pair is what tells you how coarse a pixel
      // gap is against this shape at this size.
      display: (v) => `${gapFromParam(v, false).toFixed(2)}× · ${Math.round(gapFromParam(v, true))} px`,
      hint: 'Centre to centre. At exactly one thickness consecutive shapes stand edge to edge; below it the leading edge of each one overlaps the trailing edge of the one in front, which is the look this plugin exists for. Linear in both units, because this is the control you are most likely to be matching to a number you already have.',
    },
    {
      id: 'dwell', name: 'Dwell', type: 'standard', default: 0.55, group: 'Queue',
      display: (v) => pct(dwellFromParam(v)),
      hint: 'The fraction of each shape’s own cycle it spends standing still — and the ONE dial between the two behaviours. Low: the head is still leaving as the back arrives, so the queue empties from the front while it is still filling. High: the whole train stands before anything moves, then peels off in order. Nothing in the code branches on it.',
    },
    {
      id: 'across', name: 'Across', type: 'standard', default: 0.5, group: 'Queue',
      display: (v) => acrossFromParam(v).toFixed(2),
      hint: 'Where the run sits on the other axis. It reaches past both edges so the train can sit partly off-frame and be layered with a second instance.',
    },

    //---- Timing -----------------------------------------------------------
    {
      id: 'sync', name: 'Sync', type: 'option', default: 0, group: 'Timing',
      elements: SYNC_NAMES,
      hint: 'Because phase is just a number, locking to the track costs no separate code path. See the note at the foot — this page generates its own transport at 120 BPM.',
    },
    {
      id: 'speed', name: 'Speed', type: 'standard', default: 0.574, group: 'Timing',
      display: (v) => (speedFromParam(v) === 0 ? 'stopped' : `${speedFromParam(v).toFixed(2)} /s`),
      hint: 'Cycles per second. One cycle is one shape’s whole run, and with Count shapes that is Count releases — so at 0.2 /s and 8 shapes, one arrives every 0.6 s. A dead zone at the bottom rather than a curve that merely approaches zero: "stopped" has to be a place you can land on.',
    },
    {
      id: 'phase', name: 'Phase', type: 'standard', default: 0.0, group: 'Timing',
      display: (v) => v.toFixed(3),
      hint: 'Added to the clock in every mode, and the only driver in Manual — for a keyframe, a MIDI fader, or Resolume’s own BPM-synced animation.',
    },

    //---- Colour -----------------------------------------------------------
    {
      id: 'colourMode', name: 'Colour Mode', type: 'option', default: 0, group: 'Colour',
      elements: COLOUR_MODE_NAMES,
      hint: 'Keyed off the SLOT, not the draw order, so a hue spread is a stable pattern marching through the train rather than the whole set flickering each time the queue turns over.',
    },
    { id: 'shapeR', name: 'Colour', type: 'colour', default: 1.0, group: 'Colour' },
    { id: 'shapeG', name: 'Colour_Green', type: 'colour', default: 1.0, group: 'Colour' },
    { id: 'shapeB', name: 'Colour_Blue', type: 'colour', default: 1.0, group: 'Colour' },
    { id: 'hueSpread', name: 'Hue Spread', type: 'standard', default: 1.0, group: 'Colour', display: pct },
    { id: 'opacity', name: 'Opacity', type: 'standard', default: 1.0, group: 'Colour', display: pct },
    { id: 'backR', name: 'Background', type: 'colour', default: 0.0, group: 'Colour' },
    { id: 'backG', name: 'Background_Green', type: 'colour', default: 0.0, group: 'Colour' },
    { id: 'backB', name: 'Background_Blue', type: 'colour', default: 0.0, group: 'Colour' },
    {
      id: 'backOpacity', name: 'Background Alpha', type: 'standard', default: 1.0, group: 'Colour',
      display: pct,
      hint: 'Opaque black by default, which is what a mask wants. The source only — the effect lays down the clip instead.',
    },
    {
      id: 'blend', name: 'Blend', type: 'option', default: 0, group: 'Colour',
      elements: BLEND_NAMES,
      hint: 'Three pieces of GL state rather than three branches in a loop. Max is what a mask wants — two overlapping white shapes stay white — but it is commutative, so under Max there is no "newest on top" at all. That is the right trade for a mask and the wrong one for a caterpillar, which is why Over is the default.',
    },

    //---- Shading ----------------------------------------------------------
    {
      id: 'shade', name: 'Shade', type: 'standard', default: 0.0, group: 'Shading',
      display: pct,
      hint: 'Lights the shape as though it had been inflated. The normal comes out of the distance field, so on a circle it is exactly a sphere. It earns its place here: a train of shaded shapes sliding over one another is what makes the overlap read as depth rather than as two flat shapes stacked.',
    },
    {
      id: 'light', name: 'Light', type: 'standard', default: 0.25, group: 'Shading',
      display: (v) => `${Math.round(clamp01(v) * 360)}°`,
      hint: 'Where the light comes from: one full turn over the range, 0.25 straight down from the top.',
    },

    //---- Output -----------------------------------------------------------
    {
      id: 'maskMode', name: 'Mask Mode', type: 'option', default: 0, group: 'Output',
      elements: MASK_MODE_NAMES,
      hint: 'In Shunt Mask: Reveal samples the clip inside the shape fragment, Hide punches the shapes out with a blend function, Colourise tints the clip. In Shunt, the source: Matte is white shapes on black and Inverse Matte black on white, for another layer to key against.',
    },
    {
      id: 'mix', name: 'Mix', type: 'standard', default: 1.0, group: 'Output', display: pct,
      hint: 'In Shunt Mask, the effect against the untouched clip. In Shunt, the whole output faded to transparent.',
    },

    //---- Lanes ------------------------------------------------------------
    {
      id: 'lanes', name: 'Lanes', type: 'option', default: 0, group: 'Lanes',
      elements: LANES_NAMES,
      hint: 'Whether each new set of shapes runs on a new line. A set is one cycle of releases. Step moves each set Lane Step across, wrapping; Random picks a lane at least one shape clear of the last.',
    },
    {
      id: 'laneStep', name: 'Lane Step', type: 'standard', default: 0.7, group: 'Lanes',
      display: (v) => `${Math.round(laneStepFromParam(v) * 100)}%`,
      hint: 'How far across each new set moves, as a share of the frame. Negative is up (or left); 0 at the middle of the slider.',
    },

    //---- Shadow -----------------------------------------------------------
    {
      id: 'shadow', name: 'Shadow', type: 'standard', default: 0.0, group: 'Shadow', display: pct,
      hint: 'A drop shadow on everything behind each shape, falling away from the Light. Drawn with its own shape, so it falls on the shapes it has slid over and never on itself.',
    },
    {
      id: 'shadowDistance', name: 'Shadow Distance', type: 'standard', default: 0.25, group: 'Shadow',
      display: (v) => `${shadowDistanceFromParam(v).toFixed(2)} r`,
    },
    {
      id: 'shadowBlur', name: 'Shadow Blur', type: 'standard', default: 0.3, group: 'Shadow',
      display: (v) => `${shadowBlurFromParam(v).toFixed(2)} r`,
    },

    //---- Image ------------------------------------------------------------
    {
      id: 'image', name: 'Image', type: 'option', default: 0, group: 'Image',
      elements: IMAGE_NAMES,
      hint: 'A file parameter in the plugin. Here the clip picker\'s picture stands in for the file: pick a clip, or use your own.',
    },
    {
      id: 'imageSource', name: 'Image From', type: 'option', default: 0, group: 'Image',
      elements: IMAGE_SOURCE_NAMES,
      hint: 'Single: the whole picture on every shape. Folder: every image beside the chosen file, one each (the plugin only — here it behaves as Single). Sprite Sheet: the picture cut into Columns x Rows.',
    },
    {
      id: 'columns', name: 'Columns', type: 'standard', default: 1 / 15, group: 'Image',
      display: (v) => String(columnsFromParam(v)),
    },
    {
      id: 'rows', name: 'Rows', type: 'standard', default: 1 / 15, group: 'Image',
      display: (v) => String(columnsFromParam(v)),
    },
    {
      id: 'imagePick', name: 'Pick', type: 'option', default: 0, group: 'Image',
      elements: IMAGE_PICK_NAMES,
      hint: 'Same: every shape shows the Sprite. Random: each shape its own, kept for its whole run. In Order: each shape the next one along.',
    },
    {
      id: 'sprite', name: 'Sprite', type: 'standard', default: 0, group: 'Image',
      display: (v) => String(spriteFromParam(v)),
    },
    { id: 'imageMix', name: 'Image Mix', type: 'standard', default: 1.0, group: 'Image', display: pct },
  ],

  createRenderer: (gl) => new ShuntRenderer(gl),
});
