#!/usr/bin/env python3
"""Copy the plugin's GLSL into the demo, so the two cannot be written twice.

`demo/plugin.js` carries this repo's shader text a second time, because a web
page cannot include a C++ file. `check_shaders.py` beside this one *proves* the
two copies agree; this one is how you make them agree after editing
`source/Shaders.cpp`.

It rewrites only the block between the two markers in `plugin.js`, so every
other line of that file — the ported Queue.cpp, the parameter declarations, the
page copy — is left exactly as it was.

    python3 demo/tools/sync_shaders.py          # rewrite the block
    python3 demo/tools/sync_shaders.py --check  # exit 1 if it would change

The only edits it makes to the GLSL are the two escapes a JavaScript template
literal forces — a backslash before a backtick or a `${`. Neither appears in any
shader here, and doing it anyway is what keeps the round trip exact if one ever
does.
"""

import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
SHADERS_CPP = ROOT / "source" / "Shaders.cpp"
PLUGIN_JS = ROOT / "demo" / "plugin.js"

START = "// --- shaders:start (generated by demo/tools/sync_shaders.py) ---"
END = "// --- shaders:end ---"

# C++ name -> JavaScript name, in the order they should appear.
PASSES = [
    ("kBackgroundVertexShader", "BACKGROUND_VERTEX_SHADER"),
    ("kBackgroundFragmentShader", "BACKGROUND_FRAGMENT_SHADER"),
    ("kShapeVertexShader", "SHAPE_VERTEX_SHADER"),
    ("kShapeFragmentShader", "SHAPE_FRAGMENT_SHADER"),
]


def cpp_literals(text):
    pattern = re.compile(r'const char\* const (\w+)\s*=\s*R"\((.*?)\)";', re.DOTALL)
    return {m.group(1): m.group(2) for m in pattern.finditer(text)}


def escape(source):
    """The two escapes a template literal forces, and nothing else."""
    return source.replace("`", "\\`").replace("${", "\\${")


def build_block(cpp):
    parts = [START]
    for cpp_name, js_name in PASSES:
        if cpp_name not in cpp:
            print(f"MISSING  {cpp_name} not found in source/Shaders.cpp", file=sys.stderr)
            return None
        parts.append(f"const {js_name} = `{escape(cpp[cpp_name])}`;")
        parts.append("")
    parts.append(END)
    return "\n".join(parts)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if the block would change, and write nothing")
    args = parser.parse_args()

    cpp = cpp_literals(SHADERS_CPP.read_text(encoding="utf-8"))
    block = build_block(cpp)
    if block is None:
        return 2

    text = PLUGIN_JS.read_text(encoding="utf-8")
    start = text.find(START)
    end = text.find(END)
    if start < 0 or end < 0:
        print("plugin.js has no shaders:start/shaders:end markers", file=sys.stderr)
        return 2

    updated = text[:start] + block + text[end + len(END):]

    if updated == text:
        print(f"demo/plugin.js already carries all {len(PASSES)} passes")
        return 0

    if args.check:
        print("demo/plugin.js is out of step with source/Shaders.cpp -- "
              "run demo/tools/sync_shaders.py", file=sys.stderr)
        return 1

    PLUGIN_JS.write_text(updated, encoding="utf-8")
    print(f"demo/plugin.js: rewrote {len(PASSES)} passes from source/Shaders.cpp")
    return 0


if __name__ == "__main__":
    sys.exit(main())
