/*
 * Stoatworks Labs - About window data for Shunt.
 *
 * Normally GENERATED by stoatworks-backend/scripts/sync-about.py from the
 * website's projects.json. This first copy is a hand-written provisional: the
 * project is not in projects.json yet, so there is nothing for the sync to read
 * and the guide page it names does not exist until the site is deployed.
 *
 * Re-run the sync as step 3 of release/RELEASE-CHECKLIST.md, once the
 * projects.json entry and the guide are in place, and let it overwrite this.
 * If it changes the set of links it changes kButtonCount, which changes
 * PT_COUNT -- so rebuild and re-run tools/verify.sh afterwards, not before.
 *
 * `version` here is a fallback. The build injects the real one and overrides it.
 */
#pragma once

namespace stoatworks::about
{
    inline constexpr auto name = "Shunt";
    inline constexpr auto slug = "shunt";
    inline constexpr auto hook = "Shapes that slide in, bank up and are drawn away";
    inline constexpr auto licence = "MIT";
    inline constexpr auto guide = "https://stoatworks-labs.com/software/shunt/guide/";
    inline constexpr auto page = "https://stoatworks-labs.com/software/shunt/";
    inline constexpr auto repo = "https://github.com/stoatworks-labs/shunt";
    inline constexpr auto versionFallback = "v0.1.0";

    inline constexpr auto org = "Stoatworks Labs";
    inline constexpr auto home = "https://stoatworks-labs.com";
    inline constexpr auto tagline = "Open tools for the people who run the show.";

    /* The canonical funding links, matching FUNDING.yml and the support footer. */
    struct Link { const char* name; const char* url; };
    inline constexpr Link funding[] = {
        { "GitHub Sponsors", "https://github.com/sponsors/stoatworks-labs" },
        { "Ko-fi", "https://ko-fi.com/stoatworkslabs" },
        { "Patreon", "https://patreon.com/StoatworksLabs" },
        { "Liberapay", "https://liberapay.com/stoatworks-labs" },
    };
}
